CREATE TABLE hotel (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       description TEXT,
                       brand VARCHAR(255)
);

CREATE TABLE arrival_times (
                               hotel_id BIGINT NOT NULL,
                               check_in VARCHAR(255),
                               check_out VARCHAR(255),
                               FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);

CREATE TABLE hotel_amenities (
                                 hotel_id BIGINT NOT NULL,
                                 amenity VARCHAR(255),
                                 FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);

CREATE TABLE contacts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255),
                          phone VARCHAR(255),
                          hotel_id BIGINT,
                          FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);

CREATE TABLE address (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         house_number INTEGER,
                         street VARCHAR(255),
                         city VARCHAR(255),
                         country VARCHAR(255),
                         postal_code VARCHAR(255),
                         hotel_id BIGINT,
                         FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);